version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/src/Validata.Web"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
    ignore:
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "nuget"
